//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class BookingPayment
{
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    protected global::System.Web.UI.ScriptManager ScriptManager1;
    protected global::System.Web.UI.WebControls.Button btnBack;
    protected global::System.Web.UI.WebControls.RadioButtonList rblPaymentMode;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPayment;
    protected global::System.Web.UI.WebControls.TextBox txtNameOnCard;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvName;
    protected global::System.Web.UI.WebControls.TextBox txtCardNumber;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCard;
    protected global::System.Web.UI.WebControls.RegularExpressionValidator revCard;
    protected global::System.Web.UI.WebControls.TextBox txtExpiry;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvExpiry;
    protected global::System.Web.UI.WebControls.RegularExpressionValidator revExpiry;
    protected global::System.Web.UI.WebControls.Button btnPayNow;
    protected global::System.Web.UI.WebControls.Label lblMessage;
    protected global::System.Web.UI.WebControls.ValidationSummary ValidationSummary1;
}
